"""
Django settings for SMS project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta

import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!h+_7zh1m#hw7e%qop8eax_a6ny#@#gb0bzq#b_z4v)(x6)ors'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许所有局域网设备访问
ALLOWED_HOSTS = ['192.168.1.153', '127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'products',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',  # 用于实现登出功能
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication', # 设置默认的认证类
    )
}

# 可选：设置 JWT 有效期等高级选项，这里使用默认值
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5), # 访问令牌生命周期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 刷新令牌生命周期
    # ... 更多设置
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用 mysql 后端兼容 mariadb
        'NAME': 'my_app_db',                   # 您的数据库名称
        'USER': 'app_user1',                 # 您的数据库用户名
        'PASSWORD': '123456',                # 您的数据库密码
        'HOST': '192.168.1.154',               # **MariaDB 服务器的局域网 IP 地址**
        'PORT': '3306',                        # MariaDB 端口（默认 3306）
        # ... 其他连接信息 ...
        'OPTIONS': {
            'charset': 'utf8mb4',  # <-- 在此处指定字符集
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'


USE_I18N = True # 国际化
USE_L10N = True # 本地化（格式化数字和日期）

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# 告诉 Django 额外查找根目录下的 static 文件夹
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

#用户上传的文件称为 Media
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 登录成功后跳转到首页
LOGIN_REDIRECT_URL = 'products:product_list'
# 退出登录后跳转到首页
LOGOUT_REDIRECT_URL = 'products:product_list'
# 如果未登录用户访问受限页面，跳转到登录页
LOGIN_URL = '/accounts/login/'  # 告诉装饰器：没登录就去这里

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
