# Generated by Django 4.2.27 on 2025-12-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.CharField(default=111, max_length=100, verbose_name='分类详情'),
            preserve_default=False,
        ),
    ]
